---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: geerlingguy/centos7

suites:
  - name: default
    driver:
      vm_hostname: jboss
      network:
      - ["private_network", {ip: "192.168.56.11"}]
    run_list:
      - recipe[jboss7::default]
      - recipe[jboss7::deploy]      
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:

